remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-titles-from-headings

header_pages:
  - about.md

show_downloads: false
google_analytics: [G-6GFB22D8V6]

title: "Colton Jones"

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false