remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-titles-from-headings

header_pages:
  - about.md

show_downloads: false
google_analytics: [G-6GFB22D8V6]

title: "Pages"